export const GET_POPULAR_TV_SHOWS = 'GET_POPULAR_TV_SHOWS';
export const GET_LATEST_TV_SHOWS = 'GET_LATEST_TV_SHOWS';
export const GET_TV_SHOWS_ON_AIR_ON_WEEK = 'GET_TV_SHOWS_ON_AIR_ON_WEEK';
export const GET_TV_SHOWS_ON_AIR_TODAY = 'GET_TV_SHOWS_ON_AIR_TODAY';

export const SAVE_POPULAR_TV_SHOWS = 'SAVE_POPULAR_TV_SHOWS';
export const SAVE_LATEST_TV_SHOWS = 'SAVE_LATEST_TV_SHOWS';
export const SAVE_TV_SHOWS_ON_AIR_ON_WEEK = 'SAVE_TV_SHOWS_ON_AIR_ON_WEEK';
export const SAVE_TV_SHOWS_ON_AIR_TODAY = 'SAVE_TV_SHOWS_ON_AIR_TODAY';

export const GET_TV_SHOW_DETAILS = 'GET_TV_SHOW_DETAILS';